"""empty message

Revision ID: fec59f4dc026
Revises: 6bf3b2b0bf7a
Create Date: 2023-12-10 18:01:13.133828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec59f4dc026'
down_revision = '6bf3b2b0bf7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=100), nullable=True),
    sa.Column('author_question_id', sa.Integer(), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail')
    # ### end Alembic commands ###
